use rps;

IF OBJECT_ID('PLAYER') IS NOT NULL
DROP TABLE PLAYER;

IF OBJECT_ID('TURN') IS NOT NULL
DROP TABLE TURN;

GO

CREATE TABLE PLAYER(
USERNAME NVARCHAR(100),     
PRIMARY KEY (USERNAME)
);

CREATE TABLE TURN(
USERNAME NVARCHAR(100),     
DATETIME DATETIME,

PLAYERSELECTION CHAR(8) NOT NULL CHECK (PLAYERSELECTION = 'rock' OR PLAYERSELECTION = 'paper' OR PLAYERSELECTION = 'scissors'),
AISELECTION CHAR(8) NOT NULL CHECK (AISELECTION = 'rock' OR AISELECTION = 'paper' OR AISELECTION = 'scissors'),  
PRIMARY KEY (DATETIME, USERNAME),
FOREIGN KEY (USERNAME) REFERENCES PLAYER
);

GO